export const ROUTES = {
  WELCOME: '/welcome',
  LOGIN: '/login',
  REGISTER: '/register',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  EXPENSES: '/expenses',
  ADD_EXPENSE: '/expenses/add',
  EXPENSE_BREAKDOWN: '/expenses/breakdown',
  GOALS: '/goals',
  CREATE_GOAL: '/goals/create',
  GOAL_DETAIL: '/goals/:id',
  ADD_CONTRIBUTION: '/goals/:id/add-money',
  FINANCIAL_HEALTH: '/financial-health',
  CHECKLIST_DETAIL: '/financial-health/:itemType',
  NUDGE: '/nudge',
  NUDGE_RESULT: '/nudge/result',
  BUDGET: '/budget',
  BUDGET_SUMMARY: '/budget/summary',
  LEARN: '/learn',
  LEARN_TOPIC: '/learn/topic/:topicId',
  LEARN_VIDEO: '/learn/video/:videoId',
  CHAT: '/chat',
  PROFILE: '/profile',
};
